[package]
name = "disk-usage"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-web = "1.0.0"
actix-web-actors = "1.0.0"
crossbeam = "0.7.1"
env_logger = "0.6.1"
fs2 = "0.4.3"
includedir = "0.5.0"
jwalk = "0.4.0"
log = "0.4.6"
open = "1.2.2"
phf = "0.7.24"
serde = "1.0.92"
serde_json = "1.0.39"
time = "0.1.42"
timer = "0.2.0"

[build-dependencies]
includedir_codegen = "0.5.0"
