[package]
name = "disk-usage"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
env_logger = "0.7.1"
error-chain = "0.12.1"
fs2 = "0.4.3"
futures-preview = { version = "0.3.0-alpha.19", features = ["async-await"] }
jwalk = "0.4.0"
log = "0.4.8"
open = "1.3.2"
parceljs = { git = "https://github.com/SpiralP/rust-parceljs.git", features = ["warp"] }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
tokio = "0.2.0-alpha.6"
warp = { git = "https://github.com/seanmonstar/warp.git" }
