[package]
name = "disk-usage"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
includedir = "0.5.0"
phf = "0.7.24"
actix = "0.8.3"
actix-web = "1.0.0-rc"
actix-web-actors = "1.0.0"
log = "0.4.6"
env_logger = "0.6.1"
serde = "1.0.91"
serde_json = "1.0.39"
directory-size = { path = "../rust-directory-size" }
crossbeam = "0.7.1"
timer = "0.2.0"
time = "0.1.42"
open = "1.2.2"
fs2 = "0.4.3"

[build-dependencies]
includedir_codegen = "0.5.0"
