[package]
name = "disk-usage"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
env_logger = "0.7.1"
error-chain = "0.12.1"
fs2 = "0.4.3"
futures = "0.3.4"
jwalk = "0.4.0"
log = "0.4.8"
open = "1.3.4"
parceljs = { git = "https://github.com/SpiralP/rust-parceljs.git", features = ["warp"] }
reveal = { git = "https://github.com/SpiralP/rust-reveal.git" }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.47"
tokio = { version = "0.2.11", features = ["full"] }
warp = "0.2.1"

[target.'cfg(windows)'.dependencies]
remove_dir_all = "0.5.2"
