[package]
name = "disk-usage"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
includedir = "0.5.0"
phf = "0.7.24"
actix = "0.8.1"
actix-web = "0.7.19"
log = "0.4.6"
env_logger = "0.6.1"

[build-dependencies]
includedir_codegen = "0.5.0"
