[package]
name = "disk-usage"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-web = "1.0.7"
actix-web-actors = "1.0.2"
crossbeam = "0.7.2"
env_logger = "0.6.2"
fs2 = "0.4.3"
jwalk = "0.4.0"
log = "0.4.8"
open = "1.3.2"
phf = "0.7.24"
serde = "1.0.99"
serde_json = "1.0.40"
time = "0.1.42"
timer = "0.2.0"
parceljs = { path = "../rust-parceljs" }
